openapi: 3.1.0
info:
  title: ClipNotes API
  version: 0.2.0
  description: |
    REST contract for clip registration, Hafnia-triggered analysis, monitoring data, and reasoning endpoints
    used by the ClipNotes application.
servers:
  - url: http://localhost:8000
paths:
  /healthz:
    get:
      summary: Health check
      tags: [system]
      responses:
        '200':
          description: Service is available.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /api/clips:
    post:
      summary: Register a clip
      tags: [clips]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClipCreateRequest'
      responses:
        '201':
          description: Clip registered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClipResponse'
        '400':
          description: Invalid filename provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: List recent clips
      tags: [clips]
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
          description: Number of clips to return (default 25).
      responses:
        '200':
          description: Paginated list of clips.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClipListResponse'
  /api/clips/{clip_id}:
    get:
      summary: Retrieve clip details
      tags: [clips]
      parameters:
        - name: clip_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Clip metadata and latest analysis snapshot, if any.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClipDetailResponse'
        '404':
          description: Clip not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/analysis/{clip_id}:
    post:
      summary: Trigger Hafnia analysis for a clip
      tags: [analysis]
      parameters:
        - name: clip_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalysisRequest'
      responses:
        '202':
          description: Analysis started and latest result stored.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResponse'
        '404':
          description: Clip not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: Hafnia service failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: Fetch latest analysis
      tags: [analysis]
      parameters:
        - name: clip_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Latest Hafnia analysis payload.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResponse'
        '404':
          description: Analysis not found for the clip.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/reasoning/compare:
    post:
      summary: Compare two analyzed clips and return a normalized reasoning answer.
      tags: [reasoning]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReasoningCompareRequest'
      responses:
        '200':
          description: Comparison response with evidence and metrics.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReasoningComparisonResponse'
        '400':
          description: Validation error or missing analysis data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/reasoning/chat:
    post:
      summary: Ask follow-up questions about one or more clips.
      tags: [reasoning]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReasoningChatRequest'
      responses:
        '200':
          description: Chat response with reasoning answer and evidence references.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReasoningChatResponse'
        '400':
          description: Validation error or missing analysis data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/reasoning/history:
    get:
      summary: Retrieve the most recent reasoning exchanges for selected clips.
      tags: [reasoning]
      parameters:
        - in: query
          name: clip_id
          schema:
            type: string
            format: uuid
        - in: query
          name: clip_selection_hash
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
      responses:
        '200':
          description: History list ordered by newest first.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReasoningHistoryResponse'
  /api/reasoning/metrics/{clip_id}:
    get:
      summary: Fetch derived metrics for a clip based on stored analysis JSON.
      tags: [reasoning]
      parameters:
        - in: path
          name: clip_id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Metrics payload for the requested clip.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReasoningMetricsResponse'
        '404':
          description: Clip not found or analysis missing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    HealthResponse:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [ok]
    ClipCreateRequest:
      type: object
      required: [filename]
      properties:
        filename:
          type: string
          minLength: 1
          maxLength: 255
    ClipResponse:
      type: object
      required: [clip_id, filename, status, created_at]
      properties:
        clip_id:
          type: string
          format: uuid
        filename:
          type: string
        status:
          type: string
          enum: [pending, processing, ready, failed]
        created_at:
          type: string
          format: date-time
    ClipListResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ClipSummary'
    ClipSummary:
      type: object
      required: [clip_id, filename, status, created_at]
      properties:
        clip_id:
          type: string
          format: uuid
        filename:
          type: string
        status:
          type: string
          enum: [pending, processing, ready, failed]
        created_at:
          type: string
          format: date-time
        last_analysis_at:
          type: string
          format: date-time
          nullable: true
        latency_ms:
          type: integer
          nullable: true
    ClipDetailResponse:
      type: object
      required: [clip]
      properties:
        clip:
          $ref: '#/components/schemas/ClipSummary'
        analysis:
          oneOf:
            - $ref: '#/components/schemas/AnalysisResponse'
            - type: 'null'
    AnalysisRequest:
      type: object
      properties:
        prompt:
          type: string
          maxLength: 1000
      additionalProperties: false
    AnalysisResponse:
      type: object
      required: [clip_id, summary, moments, raw, created_at]
      properties:
        clip_id:
          type: string
          format: uuid
        summary:
          type: string
        moments:
          type: array
          items:
            $ref: '#/components/schemas/Moment'
        raw:
          type: object
          additionalProperties: true
        created_at:
          type: string
          format: date-time
        latency_ms:
          type: integer
          nullable: true
        prompt:
          type: string
          nullable: true
        error_code:
          type: string
          nullable: true
        error_message:
          type: string
          nullable: true
    Moment:
      type: object
      required: [start_s, end_s, label, severity]
      properties:
        start_s:
          type: number
          minimum: 0
        end_s:
          type: number
          minimum: 0
        label:
          type: string
        severity:
          type: string
          enum: [low, medium, high]
    ReasoningCompareRequest:
      type: object
      required: [clip_a, clip_b, question]
      properties:
        clip_a:
          type: string
          format: uuid
        clip_b:
          type: string
          format: uuid
        question:
          type: string
          minLength: 1
    ReasoningComparisonResponse:
      type: object
      required: [answer, explanation, evidence]
      properties:
        answer:
          type: string
          enum: [clip_a, clip_b, equal, uncertain]
        explanation:
          type: string
        evidence:
          type: array
          items:
            $ref: '#/components/schemas/ReasoningEvidence'
        metrics:
          $ref: '#/components/schemas/ReasoningMetricsCore'
        confidence:
          type: number
          minimum: 0
          maximum: 1
    ReasoningChatRequest:
      type: object
      required: [clips, message]
      properties:
        clips:
          type: array
          minItems: 1
          items:
            type: string
            format: uuid
        message:
          type: string
          minLength: 1
    ReasoningChatResponse:
      type: object
      required: [answer, created_at]
      properties:
        answer:
          type: string
        created_at:
          type: string
          format: date-time
        evidence:
          type: array
          items:
            $ref: '#/components/schemas/ReasoningEvidence'
        clips:
          type: array
          items:
            type: string
            format: uuid
    ReasoningHistoryResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ReasoningHistoryEntry'
    ReasoningHistoryEntry:
      type: object
      required: [id, clip_ids, question, answer, created_at, answer_type]
      properties:
        id:
          type: string
          format: uuid
        clip_ids:
          type: array
          items:
            type: string
            format: uuid
        question:
          type: string
        answer:
          $ref: '#/components/schemas/ReasoningChatResponse'
        answer_type:
          type: string
          enum: [comparison, chat]
        created_at:
          type: string
          format: date-time
    ReasoningMetricsResponse:
      type: object
      required: [clip_id, counts_by_label, durations_by_label, severity_distribution]
      properties:
        clip_id:
          type: string
          format: uuid
        counts_by_label:
          type: object
          additionalProperties:
            type: integer
        durations_by_label:
          type: object
          additionalProperties:
            type: number
        severity_distribution:
          type: object
          additionalProperties:
            type: number
        object_graph:
          oneOf:
            - $ref: '#/components/schemas/GraphPayload'
            - type: 'null'
    ReasoningMetricsCore:
      type: object
      properties:
        counts_by_label:
          type: object
          additionalProperties:
            type: integer
        severity_distribution:
          type: object
          additionalProperties:
            type: number
    GraphPayload:
      type: object
      required: [nodes, edges]
      properties:
        nodes:
          type: array
          items:
            type: object
            required: [id, label]
            properties:
              id:
                type: string
              label:
                type: string
              metadata:
                type: object
                additionalProperties: true
        edges:
          type: array
          items:
            type: object
            required: [source, target]
            properties:
              source:
                type: string
              target:
                type: string
              relation:
                type: string
              metadata:
                type: object
                additionalProperties: true
    ReasoningEvidence:
      type: object
      required: [clip_id, label]
      properties:
        clip_id:
          type: string
          format: uuid
        label:
          type: string
        timestamp_range:
          type: array
          minItems: 2
          maxItems: 2
          items:
            type: number
        description:
          type: string
    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: object
          required: [code, message]
          properties:
            code:
              type: string
            message:
              type: string
  securitySchemes: {}
externalDocs:
  description: External service integrations used by ClipNotes backend.
  url: https://api.mdi.milestonesys.com/api/v1
x-external-apis:
  hafniaInference:
    openapi: 3.0.3
    info:
      title: Hafnia Inference API
      version: 0.0.8
      description: API for vision-language model completions and asset upload.
    servers:
      - url: https://api.mdi.milestonesys.com/api/v1
    security:
      - ApiKey: []
    securitySchemes:
      ApiKey:
        type: apiKey
        in: header
        name: Authorization
        description: Provide header as `ApiKey <KEY>:<SECRET>`
    paths:
      /assets:
        get:
          summary: List all assets
          operationId: listAssets
        post:
          summary: Upload an asset (mp4/mkv)
          operationId: createAsset
      /assets/{id}:
        get:
          summary: Retrieve a single asset
          operationId: getAsset
        delete:
          summary: Delete an asset
          operationId: deleteAsset
      /chat/completions:
        post:
          summary: Request a chat completion
          operationId: requestCompletion
      /chat/completions/{id}:
        get:
          summary: Retrieve completion details
          operationId: getCompletion
    schemas:
      AssetResponse:
        type: object
        properties:
          id: { type: string, format: uuid }
          name: { type: string }
          created_at: { type: string, format: date-time }
      ChoicesResponse:
        type: object
        properties:
          id: { type: string, format: uuid }
          choices:
            type: array
            items:
              type: object
              properties:
                index: { type: integer }
                message:
                  type: object
                  properties:
                    role: { type: string, enum: [assistant] }
                    content: { type: string }
